#!/bin/bash

dropdb --if-exists CRM_db 
createdb CRM_db
mkdir -p /home/postgres/CRM
cp -Rv /app/schema/schema_crm /home/postgres/CRM/
psql postgresql://postgres:example@localhost/CRM_db << AAA

  CREATE EXTENSION postgis;
  SELECT PostGIS_Version();

  \i '/home/postgres/CRM/schema/sql/CRM_polygon_traces.sql';
  \i '/home/postgres/CRM/schema/sql/setup_schema.sql';
  \i '/home/postgres/CRM/schema/sql/load_regions.sql';
  \i '/home/postgres/CRM/schema/sql/linkup_traces.sql';

  DROP ROLE webonly;
  CREATE ROLE webonly WITH LOGIN PASSWORD 'scec';
  GRANT SELECT ON ALL TABLES IN SCHEMA public TO webonly;
  REVOKE CREATE ON SCHEMA public FROM PUBLIC;

  SELECT UpdateGeometrySRID('trace_tb','geom',4326);

  \dp
  \q

AAA
