# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    build:
      dockerfile: Dockerfile-postgis
      context: ./
    restart: always
    environment:
      name: edric
      POSTGRES_PASSWORD: example

  web:
    build:
      dockerfile: Dockerfile-web
      context: ./
    restart: always
    environment:
      CFM_MY_DB: CFM6_preferred_db 
      CFM_MY_OPTION: 0
      CFM_MY_PORT: 8084
      CFM_MY_BLIND: CFM6.1_blind.utm
      CFM_MY_TRACE: CFM6.1_traces.utm
      CFM_PROD_PATH: "/research/cfm-viewer/6.1/preferred"
    ports:
      - "8084:8081"

  altweb:
    build:
      dockerfile: Dockerfile-web
      context: ./
    restart: always
    environment:
      CFM_MY_DB: CFM6_alt_db 
      CFM_MY_OPTION: 1
      CFM_MY_PORT: 8086 
      CFM_MY_BLIND: CFM6.1_blind_Alt.utm
      CFM_MY_TRACE: CFM6.1_traces_Alt.utm
      CFM_PROD_PATH: "/research/cfm-viewer/6.1/alternatives"
    ports:
      - "8086:8081"

  rupweb:
    build:
      dockerfile: Dockerfile-web
      context: ./
    restart: always
    environment:
      CFM_MY_DB: CFM6_rup_db
      CFM_MY_OPTION: 2
      CFM_MY_PORT: 8088
      CFM_MY_BLIND: CFM6.1_blind_Rup.utm
      CFM_MY_TRACE: CFM6.1_traces_Rup.utm
      CFM_PROD_PATH: "/research/cfm-viewer/6.1/ruptures"
    ports:
      - "8088:8081"

  old53web:
    build:
      dockerfile: Dockerfile-web
      context: ./
    restart: always
    environment:
      CFM_MY_DB: CFM53_preferred_db
      CFM_MY_OPTION: 3
      CFM_MY_PORT: 8090
      CFM_MY_BLIND: CFM5.3_blind.utm
      CFM_MY_TRACE: CFM5.3_traces.utm
      CFM_PROD_PATH: "/research/cfm-viewer/5.3/preferred"
    ports:
      - "8090:8081"

#cfm_web_db  0.0.0.0:5432->5432/tcp, :::5432->5432/tcp cfm_web_db_1
#cfm_web_web 0.0.0.0:8083->80/tcp, :::8083->80/tcp, 0.0.0.0:8082->8081/tcp, :::8082->8081/tcp   cfm_web_web_1
#cgm_web_db  0.0.0.0:5433->5432/tcp, :::5433->5432/tcp  cgm_web_db_1
#cgm_web_web 0.0.0.0:8085->80/tcp, :::8085->80/tcp, 0.0.0.0:8084->8081/tcp, :::8084->8081/tcp   cgm_web_web_1
