# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    build:
      dockerfile: Dockerfile-postgis
      context: ./
    restart: always
    environment:
      name: edric
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  web:
    build:
      dockerfile: Dockerfile-web
      context: ./
    ports:
      - 8081:8081
      - 8080:80

