FROM amazonlinux

WORKDIR /app

COPY . /app

# RUN /app/doc/run-for-httpd
RUN yum install -y httpd && \
	amazon-linux-extras install -y php7.2 && \
	yum install -y php php-pgsql 

# RUN /app/doc/install-composer.sh

COPY ./doc/cfm.conf /etc/httpd/conf.d/

CMD ["apachectl", "-D", "FOREGROUND"]

