# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    build:
      dockerfile: Dockerfile-postgis
      context: ./
    restart: always
    environment:
      name: edric
      POSTGRES_PASSWORD: example

  web:
    build:
      dockerfile: Dockerfile-web
      context: ./
    restart: always
    environment:
      CFM_MY_DB: CFM7_preferred_db 
      CFM_MY_OPTION: 0
      CFM_MY_PORT: 8104
      CFM_MY_BLIND: CFM7.0_blind.utm
      CFM_MY_TRACE: CFM7.0_traces.utm
      CFM_PROD_PATH: "research/cfm-viewer/7.0/preferred"
    ports:
      - "8104:8081"
      - "8105:80"

  altweb:
    build:
      dockerfile: Dockerfile-web
      context: ./
    restart: always
    environment:
      CFM_MY_DB: CFM7_alt_db 
      CFM_MY_OPTION: 1
      CFM_MY_PORT: 8106 
      CFM_MY_BLIND: CFM7.0_blind_Alt.utm
      CFM_MY_TRACE: CFM7.0_traces_Alt.utm
      CFM_PROD_PATH: "research/cfm-viewer/7.0/alternatives"
    ports:
      - "8106:8081"
      - "8107:80"

  rupweb:
    build:
      dockerfile: Dockerfile-web
      context: ./
    restart: always
    environment:
      CFM_MY_DB: CFM7_rup_db
      CFM_MY_OPTION: 2
      CFM_MY_PORT: 8108
      CFM_MY_BLIND: CFM7.0_blind_Rup.utm
      CFM_MY_TRACE: CFM7.0_traces_Rup.utm
      CFM_PROD_PATH: "research/cfm-viewer/7.0/ruptures"
    ports:
      - "8108:8081"
      - "8109:80"


  old61web:
    build:
      dockerfile: Dockerfile-web
      context: ./
    restart: always
    environment:
      CFM_MY_DB: CFM6_preferred_db 
      CFM_MY_OPTION: 3
      CFM_MY_PORT: 8084
      CFM_MY_BLIND: CFM6.1_blind.utm
      CFM_MY_TRACE: CFM6.1_traces.utm
      CFM_PROD_PATH: "research/cfm-viewer/6.1/preferred"
    ports:
      - "8084:8081"
      - "8085:80"

  old61altweb:
    build:
      dockerfile: Dockerfile-web
      context: ./
    restart: always
    environment:
      CFM_MY_DB: CFM6_alt_db 
      CFM_MY_OPTION: 4
      CFM_MY_PORT: 8086 
      CFM_MY_BLIND: CFM6.1_blind_Alt.utm
      CFM_MY_TRACE: CFM6.1_traces_Alt.utm
      CFM_PROD_PATH: "research/cfm-viewer/6.1/alternatives"
    ports:
      - "8086:8081"
      - "8087:80"

  old61rupweb:
    build:
      dockerfile: Dockerfile-web
      context: ./
    restart: always
    environment:
      CFM_MY_DB: CFM6_rup_db
      CFM_MY_OPTION: 5
      CFM_MY_PORT: 8088
      CFM_MY_BLIND: CFM6.1_blind_Rup.utm
      CFM_MY_TRACE: CFM6.1_traces_Rup.utm
      CFM_PROD_PATH: "research/cfm-viewer/6.1/ruptures"
    ports:
      - "8088:8081"
      - "8089:80"

  old53web:
    build:
      dockerfile: Dockerfile-web
      context: ./
    restart: always
    environment:
      CFM_MY_DB: CFM53_preferred_db
      CFM_MY_OPTION: 6
      CFM_MY_PORT: 8090
      CFM_MY_BLIND: CFM5.3_blind.utm
      CFM_MY_TRACE: CFM5.3_traces.utm
      CFM_PROD_PATH: "research/cfm-viewer/5.3/preferred"
    ports:
      - "8090:8081"
      - "8091:80"
