FROM mdillon/postgis:10-alpine
ENV POSTGRES_USER postgres
ENV POSTGRES_DB cfm_db
ENV PGDATA=/home/postgres/cfm_db

WORKDIR /app

COPY . /app

RUN cd /app/schema/data && \
    wget https://files.scec.org/s3fs-public/projects/cfm/seismicity/cfm-v7.0-seismicity-data.tar.gz &&\
    tar zxvf cfm-v7.0-seismicity-data.tar.gz

RUN mkdir /home/postgres
RUN chown postgres /home/postgres
RUN su postgres -c /app/doc/run-as-postgres

RUN echo "host all  all    0.0.0.0/0  trust" >> /home/postgres/cfm_db/pg_hba.conf

# RUN su postgres -c "pg_ctl -D /home/postgres/cfm_db -l /home/postgres/logfile start"


