# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    build:
      dockerfile: Dockerfile-postgis
      context: ./
    restart: always
    environment:
      name: edric
      POSTGRES_PASSWORD: example

  web:
    build:
      dockerfile: Dockerfile-web
      context: ./
    restart: always
    environment:
      CFM_MY_DB: CFM7_preferred_db 
      CFM_MY_OPTION: 0
      CFM_MY_PORT: 8104
      CFM_MY_BLIND: CFM7.0_blind.utm
      CFM_MY_TRACE: CFM7.0_traces.utm
      CFM_PROD_PATH: "research/cfm-explorer"
    ports:
      - "8104:8081"
      - "8105:80"

