version: '2.2'

services:

  db:
    mem_limit: 5g
    cpus: 3

  web:
    mem_limit: 5g
    cpus: 3

  altweb:
     mem_limit: 5g
     cpus: 3

  rupweb:
     mem_limit: 5g
     cpus: 3

  old53web:
     mem_limit: 5g
     cpus: 3

