FROM amazonlinux:2

WORKDIR /app

COPY . /app


#RUN amazon-linux-extras enable epel && \
#    yum install -y epel-release && \
#    yum update && \
#    yum install -y httpd && \
#    amazon-linux-extras install -y php7.2 && \
#    yum install -y php php-pgsql wget tar proj


RUN yum update -y && \
    yum install -y amazon-linux-extras && \
    amazon-linux-extras enable epel && \
    yum install -y epel-release && \
    yum install -y httpd wget tar proj && \
    amazon-linux-extras enable php7.2 && \
    yum clean metadata && \
    yum install -y php php-pgsql


#RUN sudo amazon-linux-extra enable epel && \
#    yum install -y epel-release && \
#    yum update && \
#    yum install -y httpd && \
#    yum install -y php7.2 && \
#    yum install -y php php-pgsql wget tar proj
    

#RUN cd /app/web/cfm_data && \
#    wget https://files.scec.org/s3fs-public/projects/cfm/seismicity/cfm-v7.0-seismicity-utm.tar.gz &&\
#    tar zxvf cfm-v7.0-seismicity-utm.tar.gz

COPY ./doc/cfm.conf /etc/httpd/conf.d/
COPY ./custom-php.ini /etc/php.d/custom-php.ini

CMD ["apachectl", "-D", "FOREGROUND"]

