# Use postgres/example user/password credentials
version: '2.2'

services:

  db:
    build:
      dockerfile: Dockerfile-postgis
      context: ./
    restart: always
    environment:
      name: edric
      POSTGRES_PASSWORD: example

  altweb:
    build:
      dockerfile: Dockerfile-web
      context: ./
    restart: always
    ports:
#      - 80:8081
      - 8086:8081
      - 8087:80

