#!/bin/sh

#DATATYPE="preferred53"
#DATATYPE="alternatives6"
#DATATYPE="preferred6"
DATATYPE="ruptures6"

./extract-csv.sh ${DATATYPE}
mv *.csv ../data/${DATATYPE}

./convert-shp.sh ${DATATYPE}
mv *.sql ../sql/${DATATYPE}

./create-csv.sh ${DATATYPE}
mv *.csv ../data/${DATATYPE}

./create-sql.sh ${DATATYPE}
mv *.sql ../sql/${DATATYPE}
mv *column_labels ../data/${DATATYPE}

