#!/bin/sh

#TOGGLE_TYPE="P5"
#TOGGLE_TYPE="P6"
#TOGGLE_TYPE="A6"
TOGGLE_TYPE="R6"

. ./common.sh

echo "GOING to " ${DATATYPE}

./extract-csv.sh
mv *.csv ../data/${DATATYPE}
./convert-shp.sh
mv *.sql ../sql/${DATATYPE}
./create-csv.sh
mv *.csv ../data/${DATATYPE}
./create-sql.sh
mv *.sql ../sql/${DATATYPE}
mv *column_labels ../data/${DATATYPE}

