#!/bin/bash

dropdb --if-exists CFM53_db 
createdb CFM53_db
mkdir -p /home/postgres/CFM
cp -Rv /app/schema /home/postgres/CFM/
(cd /home/postgres/CFM/schema/data; gunzip eq_tb.csv.gz)
psql postgresql://postgres:example@localhost/CFM53_db << AAA

  CREATE EXTENSION postgis;
  SELECT PostGIS_Version();

  \i '/home/postgres/CFM/schema/sql/CFM53_preferred_traces_nonblind.sql';
  \i '/home/postgres/CFM/schema/sql/CFM53_preferred_traces_blind.sql';
  \i '/home/postgres/CFM/schema/sql/setup_schema.sql';
  \i '/home/postgres/CFM/schema/sql/setup_tbs.sql';
  \i '/home/postgres/CFM/schema/sql/setup_object_tb.sql';
  \i '/home/postgres/CFM/schema/sql/linkup_traces.sql';
  \i '/home/postgres/CFM/schema/sql/add_foreign_key.sql';

  DROP ROLE webonly;
  CREATE ROLE webonly WITH LOGIN PASSWORD 'scec';
  GRANT SELECT ON ALL TABLES IN SCHEMA public TO webonly;
  REVOKE CREATE ON SCHEMA public FROM PUBLIC;

  SELECT UpdateGeometrySRID('trace_tb','geom',4326);

  \dp
  \q

AAA
