#!/bin/bash

mkdir -p /home/postgres/CFM
cp -Rv /app/schema /home/postgres/CFM/

(cd /home/postgres/CFM/schema/data; gunzip eq_HaukssonWaldhauser_1_tb.csv.gz)
(cd /home/postgres/CFM/schema/data; gunzip eq_HaukssonWaldhauser_2_tb.csv.gz)
(cd /home/postgres/CFM/schema/data; gunzip eq_HaukssonWaldhauser_3_tb.csv.gz)
(cd /home/postgres/CFM/schema/data; gunzip eq_HaukssonWaldhauser_4_tb.csv.gz)

