INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (1,'Asthenosphere',0,'#786D5F',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (2,'Upper Mantle',0,'#FF0000',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (3,'Sierra Nevada (E)',0,'#B041FF',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (4,'Colorado Plateau',0,'#614051',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (5,'Sierra Nevada (W)',0,'#4A148C',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (6,'Peninsular Range (W)',0,'#7B1FA2',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (7,'Basin and Range',0,'#D84315',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (8,'Peninsular Range (W)',1,'#9C27B0',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (9,'Southern Walker Lane',0,'#FF6F00',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (10,'Peninsular Range (E)',0,'#6A1B9A',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (11,'Gulf Rifted Margin',1,'#D84315',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (12,'San Gabriel',1,'#3090C7',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (13,'Mojavia',0,'#3090C7',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (14,'San Gabriel',1,'#3090C7',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (15,'San Gabriel',1,'#3090C7',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (16,'Salinia',0,'#3090C7',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (17,'San Gabriel',1,'#3090C7',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (18,'Great Valley',0,'#FFD801',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (19,'San Gabriel',0,'#3090C7',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (20,'Santa Maria Rift',0,'#FFA62F',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (21,'San Gabriel',1,'#3090C7',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (22,'Gulf Rifted Margin',0,'#EF6C00',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (23,'Western Transverse Ranges',0,'#FFD801',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (24,'Santa Maria Rift',1,'#FFA62F',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (25,'Inner Borderland Rift',0,'#FFA62F',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (26,'Western Transverse Ranges',1,'#FFD801',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (27,'Nicolas Terrane',0,'#FFD801',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (28,'Rift Axis 2',0,'#D462FF',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (29,'San Francisco Bay',0,'#347C17',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (30,'Peninsular Range (E)',1,'#9172EC',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (31,'Rift Axis 1',0,'#D462FF',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (32,'Peninsular Range (E)',1,'#7F38EC',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (33,'Rift Axis 3',0,'#D462FF',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (34,'Accretionary Prism (S)',0,'#347C17',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (35,'Accretionary Prism (N)',0,'#347C17',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (36,'Oceanic Crust',0,'#6C2DC7',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (37,'San Gabriel',1,'#3090C7',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (38,'San Gabriel',1,'#3090C7',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (39,'San Gabriel',1,'#3090C7',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (40,'San Gabriel',1,'#3090C7',1);
INSERT INTO REGION_tb ("domain_id","name","sliver","color","state") VALUES (41,'Above Ground',0,'#FFFFFF',1);
